
###############################################################################
#
# Inclusive Makefile for the arm_accton_as4610 module.
#
# Autogenerated 2016-04-03 19:55:05.384384
#
###############################################################################
arm_accton_as4610_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

