
###############################################################################
#
# Inclusive Makefile for the libonlp-arm-accton-as4610 module.
#
# Autogenerated 2016-04-03 19:55:05.365431
#
###############################################################################
libonlp-arm-accton-as4610_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

