
###############################################################################
#
# Inclusive Makefile for the x86_64_accton_as7112_54x module.
#
# Autogenerated 2018-09-12 02:07:07.665347
#
###############################################################################
x86_64_accton_as7112_54x_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_accton_as7112_54x_BASEDIR)module/make.mk
include $(x86_64_accton_as7112_54x_BASEDIR)module/src/make.mk
include $(x86_64_accton_as7112_54x_BASEDIR)module/auto/make.mk

