
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn2010 module.
#
# Autogenerated 2019-07-13 17:21:14.110508
#
###############################################################################
x86_64_mlnx_msn2010_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn2010_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn2010_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn2010_BASEDIR)module/src/make.mk

