
###############################################################################
#
# Inclusive Makefile for the quanta_sys_eeprom module.
#
# Autogenerated 2014-08-03 09:25:20.039252
#
###############################################################################
quanta_sys_eeprom_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(quanta_sys_eeprom_BASEDIR)/module/make.mk
include $(quanta_sys_eeprom_BASEDIR)/module/auto/make.mk
include $(quanta_sys_eeprom_BASEDIR)/module/src/make.mk
include $(quanta_sys_eeprom_BASEDIR)/utest/_make.mk

