
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-kvm-x86-64 module.
#
# Autogenerated 2016-03-16 22:11:47.698846
#
###############################################################################
libonlp-x86-64-kvm-x86-64_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

