#!/bin/sh
############################################################
#
# Invoke onlpm.py in the local directory.
#
############################################################
ONLPM_PY=${ONLPM_PY:-onlpm.py}
$ONLPM_PY "$@"
