
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-delta-agc7648a module.
#
# Autogenerated 2017-03-15 04:06:44.303111
#
###############################################################################
libonlp-x86-64-delta-agc7648a_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

