
###############################################################################
#
# Inclusive Makefile for the oom_shim module.
#
# Autogenerated 2016-02-16 12:05:28.510482
#
###############################################################################
oom_shim_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(oom_shim_BASEDIR)/module/make.mk
include $(oom_shim_BASEDIR)/module/auto/make.mk
include $(oom_shim_BASEDIR)/module/src/make.mk
include $(oom_shim_BASEDIR)/utest/_make.mk

