
###############################################################################
#
# Inclusive Makefile for the oom-shim module.
#
# Autogenerated 2016-02-12 16:50:50.721882
#
###############################################################################
oom-shim_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(oom-shim_BASEDIR)/module/make.mk
include $(oom-shim_BASEDIR)/utest/_make.mk

