
###############################################################################
#
# Inclusive Makefile for the x86_64_inventec_d6556 module.
#
# Autogenerated 2018-11-30 07:22:11.055018
#
###############################################################################
x86_64_inventec_d6556_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_inventec_d6556_BASEDIR)module/make.mk
include $(x86_64_inventec_d6556_BASEDIR)module/src/make.mk
include $(x86_64_inventec_d6556_BASEDIR)module/auto/make.mk

