
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-delta-ag7648 module.
#
# Autogenerated 2017-03-20 15:05:28.120004
#
###############################################################################
libonlp-x86-64-delta-ag7648_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

