
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn4700 module.
#
# Autogenerated 2019-07-30 18:51:23.685946
#
###############################################################################
x86_64_mlnx_msn4700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn4700_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn4700_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn4700_BASEDIR)module/src/make.mk

