
###############################################################################
#
# Inclusive Makefile for the oom-shim module.
#
# Autogenerated 2016-02-15 20:59:29.632190
#
###############################################################################
oom-shim_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

