
###############################################################################
#
# Inclusive Makefile for the x86_64_alphanetworks_snx60a0_486f module.
#
# Autogenerated 2016-07-15 15:47:05.304474
#
###############################################################################
x86_64_alphanetworks_snx60a0_486f_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_alphanetworks_snx60a0_486f_BASEDIR)module/make.mk
include $(x86_64_alphanetworks_snx60a0_486f_BASEDIR)module/auto/make.mk
include $(x86_64_alphanetworks_snx60a0_486f_BASEDIR)module/src/make.mk
include $(x86_64_alphanetworks_snx60a0_486f_BASEDIR)utest/_make.mk

