
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-ingrasys-s9230-64x module.
#
# Autogenerated 2018-08-10 02:00:54.722838
#
###############################################################################
libonlp-x86-64-ingrasys-s9230-64x_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

