
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn3800 module.
#
# Autogenerated 2019-08-16 10:03:53.580098
#
###############################################################################
x86_64_mlnx_msn3800_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn3800_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn3800_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn3800_BASEDIR)module/src/make.mk

