
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-delta-ag7648c module.
#
# Autogenerated 2017-03-20 15:05:28.120004
#
###############################################################################
libonlp-x86-64-delta-ag7648c_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

