
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-delta-ag5648 module.
#
# Autogenerated 2017-03-15 04:06:44.303111
#
###############################################################################
libonlp-x86-64-delta-ag5648_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

