
###############################################################################
#
# Inclusive Makefile for the libonlp-arm64-nxp-ls1046ardb module.
#
# Autogenerated 2018-04-23 11:35:14.871796
#
###############################################################################
libonlp-arm64-nxp-ls1046ardb_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

