
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_mqm8700 module.
#
# Autogenerated 2019-08-16 10:04:47.420022
#
###############################################################################
x86_64_mlnx_mqm8700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_mqm8700_BASEDIR)module/make.mk
include $(x86_64_mlnx_mqm8700_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_mqm8700_BASEDIR)module/src/make.mk

