
###############################################################################
#
# Inclusive Makefile for the arm_qemu_armv7a module.
#
# Autogenerated 2016-03-31 14:50:33.145280
#
###############################################################################
arm_qemu_armv7a_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

