
###############################################################################
#
# Inclusive Makefile for the libonlp-arm-qemu-armv7a module.
#
# Autogenerated 2016-03-31 14:50:19.497986
#
###############################################################################
libonlp-arm-qemu-armv7a_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

