
###############################################################################
#
# Inclusive Makefile for the libonlp-arm-accton-as4610-54 module.
#
# Autogenerated 2016-04-03 19:55:05.365431
#
###############################################################################
libonlp-arm-accton-as4610-54_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

