
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-inventec-d6356 module.
#
# Autogenerated 2018-11-30 07:22:16.900798
#
###############################################################################
libonlp-x86-64-inventec-d6356_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

