
###############################################################################
#
# Inclusive Makefile for the x86_64_delta_ag7648 module.
#
# Autogenerated 2017-03-20 15:05:23.627200
#
###############################################################################
x86_64_delta_ag7648_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_delta_ag7648_BASEDIR)module/make.mk
include $(x86_64_delta_ag7648_BASEDIR)module/auto/make.mk
include $(x86_64_delta_ag7648_BASEDIR)module/src/make.mk

