
###############################################################################
#
# Inclusive Makefile for the quanta_sys_eeprom module.
#
# Autogenerated 2015-11-13 21:30:58.392873
#
###############################################################################
quanta_sys_eeprom_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

