
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn27002 module.
#
# Autogenerated 2019-08-16 10:03:42.708282
#
###############################################################################
x86_64_mlnx_msn27002_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn27002_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn27002_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn27002_BASEDIR)module/src/make.mk

