
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-mlnx-mqm8700-r0 module.
#
# Autogenerated 2015-12-23 23:45:22.249911
#
###############################################################################
libonlp-x86-64-mlnx-mqm8700-r0_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

