
###############################################################################
#
# Inclusive Makefile for the onlp_platform_sim module.
#
# Autogenerated 2017-11-26 18:25:08.446534
#
###############################################################################
onlp_platform_sim_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(onlp_platform_sim_BASEDIR)module/make.mk
include $(onlp_platform_sim_BASEDIR)module/auto/make.mk
include $(onlp_platform_sim_BASEDIR)module/src/make.mk

