#ifndef __X86_64_QUANTA_IX7_RGLBMC_GPIO_TABLE_H__
#define __X86_64_QUANTA_IX7_RGLBMC_GPIO_TABLE_H__

/*
 * defined within platform/quanta_switch.c
 * Quanta Switch Platform driver
 */
#define QUANTA_IX7_PCA953x_GPIO(P1, P2)	(P1*8+P2)

#define QUANTA_IX7_PCA9555_GPIO_SIZE	0x10

#define QUANTA_IX7_I2C_GPIO_BASE	0x10

#define QUANTA_IX7_I2C_GPIO_CPU_BASE               0x20

#define QUANTA_IX7_CPU_BOARD_GPIO_BASE              (QUANTA_IX7_I2C_GPIO_CPU_BASE)
#define QUANTA_IX7_CPU_BOARD_SYS_P1                 (QUANTA_IX7_CPU_BOARD_GPIO_BASE + QUANTA_IX7_PCA953x_GPIO(1,2))
#define QUANTA_IX7_CPU_BOARD_SYS_P2                 (QUANTA_IX7_CPU_BOARD_GPIO_BASE + QUANTA_IX7_PCA953x_GPIO(1,3))

#define QUANTA_IX7_ZQSFP_EN_GPIO_BASE				QUANTA_IX7_I2C_GPIO_BASE
#define QUANTA_IX7_ZQSFP_EN_GPIO_SIZE				QUANTA_IX7_PCA9555_GPIO_SIZE
#define QUANTA_IX7_ZQSFP_EN_GPIO_P3V3_PW_GD		(QUANTA_IX7_ZQSFP_EN_GPIO_BASE + QUANTA_IX7_PCA953x_GPIO(0,4))
#define QUANTA_IX7_ZQSFP_EN_GPIO_P3V3_PW_EN		(QUANTA_IX7_ZQSFP_EN_GPIO_BASE + QUANTA_IX7_PCA953x_GPIO(0,5))

#endif /* __X86_64_QUANTA_IX7_RGLBMC_GPIO_TABLE_H__ */
