
###############################################################################
#
# Inclusive Makefile for the x86_64_inventec_d6556 module.
#
# Autogenerated 2019-07-30 18:54:08.500975
#
###############################################################################
x86_64_inventec_d6556_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_inventec_d6556_BASEDIR)module/make.mk
include $(x86_64_inventec_d6556_BASEDIR)module/auto/make.mk
include $(x86_64_inventec_d6556_BASEDIR)module/src/make.mk

