
###############################################################################
#
# Inclusive Makefile for the libonlp-arm64-nxp-ls1043ardb module.
#
# Autogenerated 2018-04-23 06:16:07.559855
#
###############################################################################
libonlp-arm64-nxp-ls1043ardb_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

