
###############################################################################
#
# Inclusive Makefile for the x86_64_accton_as7112_54x module.
#
# Autogenerated 2019-07-13 17:26:43.980186
#
###############################################################################
x86_64_accton_as7112_54x_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_accton_as7112_54x_BASEDIR)module/make.mk
include $(x86_64_accton_as7112_54x_BASEDIR)module/auto/make.mk
include $(x86_64_accton_as7112_54x_BASEDIR)module/src/make.mk

