
###############################################################################
#
# Inclusive Makefile for the arm64_nxp_layerscape module.
#
# Autogenerated 2017-12-18 11:06:48.148999
#
###############################################################################
arm64_nxp_layerscape_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arm64_nxp_layerscape_BASEDIR)module/make.mk
include $(arm64_nxp_layerscape_BASEDIR)module/src/make.mk
include $(arm64_nxp_layerscape_BASEDIR)module/auto/make.mk

