
###############################################################################
#
# Inclusive Makefile for the libonlp-arm-delta-ag6248c-poe module.
#
# Autogenerated 2016-07-20 18:27:47.344268
#
###############################################################################
libonlp-arm-delta-ag6248c-poe_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

