
###############################################################################
#
# Inclusive Makefile for the sff module.
#
# Autogenerated 2014-08-14 16:23:30.067308
#
###############################################################################
sff_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(sff_BASEDIR)/module/make.mk
include $(sff_BASEDIR)/module/auto/make.mk
include $(sff_BASEDIR)/module/src/make.mk
include $(sff_BASEDIR)/utest/_make.mk

