
###############################################################################
#
# Inclusive Makefile for the x86_64_delta_ag7648c module.
#
# Autogenerated 2019-07-30 18:47:54.130804
#
###############################################################################
x86_64_delta_ag7648c_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_delta_ag7648c_BASEDIR)module/make.mk
include $(x86_64_delta_ag7648c_BASEDIR)module/auto/make.mk
include $(x86_64_delta_ag7648c_BASEDIR)module/src/make.mk

