
###############################################################################
#
# Inclusive Makefile for the onlplib module.
#
# Autogenerated 2017-05-26 00:39:15.535760
#
###############################################################################
onlplib_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(onlplib_BASEDIR)module/make.mk
include $(onlplib_BASEDIR)module/auto/make.mk
include $(onlplib_BASEDIR)module/src/make.mk
include $(onlplib_BASEDIR)utest/_make.mk

