
###############################################################################
#
# Inclusive Makefile for the arm64_nxp_layerscape module.
#
# Autogenerated 2018-04-23 06:15:46.784359
#
###############################################################################
arm64_nxp_layerscape_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arm64_nxp_layerscape_BASEDIR)module/make.mk
include $(arm64_nxp_layerscape_BASEDIR)module/src/make.mk
include $(arm64_nxp_layerscape_BASEDIR)module/auto/make.mk

