
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn2740 module.
#
# Autogenerated 2019-07-13 17:21:06.142770
#
###############################################################################
x86_64_mlnx_msn2740_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn2740_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn2740_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn2740_BASEDIR)module/src/make.mk

