
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn2740 module.
#
# Autogenerated 2019-08-16 10:04:25.647570
#
###############################################################################
x86_64_mlnx_msn2740_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn2740_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn2740_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn2740_BASEDIR)module/src/make.mk

