
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn3700 module.
#
# Autogenerated 2019-07-13 17:20:55.933813
#
###############################################################################
x86_64_mlnx_msn3700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn3700_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn3700_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn3700_BASEDIR)module/src/make.mk

