
###############################################################################
#
# Inclusive Makefile for the libonlp-arm64-nxp-ls2088ardb module.
#
# Autogenerated 2018-04-23 11:35:06.218209
#
###############################################################################
libonlp-arm64-nxp-ls2088ardb_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

