############################################################
#
# Convenience makefile for generating
# the local version variables.
#
versions.env:
	$(ONL_V_at) $(MAKE) -f versions.mk ONL_VERSION_ENV_FILE=versions.env

