
###############################################################################
#
# Inclusive Makefile for the arm_delta_ag6248c module.
#
# Autogenerated 2019-07-30 18:47:57.006136
#
###############################################################################
arm_delta_ag6248c_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arm_delta_ag6248c_BASEDIR)module/make.mk
include $(arm_delta_ag6248c_BASEDIR)module/auto/make.mk
include $(arm_delta_ag6248c_BASEDIR)module/src/make.mk

