
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_mqm8700 module.
#
# Autogenerated 2015-12-23 23:45:56.754200
#
###############################################################################
x86_64_mlnx_mqm8700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_mqm8700_BASEDIR)/module/make.mk
include $(x86_64_mlnx_mqm8700_BASEDIR)/module/auto/make.mk
include $(x86_64_mlnx_mqm8700_BASEDIR)/module/src/make.mk

