
###############################################################################
#
# Inclusive Makefile for the libonlp-arm64-nxp-ls1088ardb module.
#
# Autogenerated 2018-04-23 11:35:09.987287
#
###############################################################################
libonlp-arm64-nxp-ls1088ardb_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

