
###############################################################################
#
# Inclusive Makefile for the libonlp-arm-accton-as4610-30 module.
#
# Autogenerated 2016-07-20 18:29:31.706331
#
###############################################################################
libonlp-arm-accton-as4610-30_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

