
###############################################################################
#
# Inclusive Makefile for the arm64_nxp_ls2080ardb module.
#
# Autogenerated 2016-04-03 19:55:05.384384
#
###############################################################################
arm64_nxp_ls2080ardb_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

