
###############################################################################
#
# Inclusive Makefile for the libonlp-arm64-nxp-ls2080ardb module.
#
# Autogenerated 2016-06-08 10:25:29.125218
#
###############################################################################
libonlp-arm64-nxp-ls2080ardb_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

