
help:
	@echo "Targets:"
	@echo "  clean : Clean all extracts and debian packages."

clean:
	@find packages -name "*.deb" -delete
	@find packages -name Packages -delete
	@find packages -name Packages.gz -delete
	@rm -rf extracts

