
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-mlnx-qmb700 module.
#
# Autogenerated 2016-10-13 22:58:39.095824
#
###############################################################################
libonlp-x86-64-mlnx-qmb700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

