
###############################################################################
#
# Inclusive Makefile for the x86_64_inventec_d10064 module.
#
# Autogenerated 2019-09-23 07:32:10.562583
#
###############################################################################
x86_64_inventec_d10064_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_inventec_d10064_BASEDIR)module/make.mk
include $(x86_64_inventec_d10064_BASEDIR)module/auto/make.mk
include $(x86_64_inventec_d10064_BASEDIR)module/src/make.mk

