
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn3510 module.
#
# Autogenerated 2020-01-31 14:15:04.714355
#
###############################################################################
x86_64_mlnx_msn3510_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn3510_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn3510_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn3510_BASEDIR)module/src/make.mk

