
###############################################################################
#
# Inclusive Makefile for the x86_64_accton_as7512_32x module.
#
# Autogenerated 2015-12-23 20:42:53.224637
#
###############################################################################
x86_64_accton_as7512_32x_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_accton_as7512_32x_BASEDIR)/module/make.mk
include $(x86_64_accton_as7512_32x_BASEDIR)/module/auto/make.mk
include $(x86_64_accton_as7512_32x_BASEDIR)/module/src/make.mk

